Repository Mergifyio/mergify-cli, pull requests merged in 2023-07, with the labels that each got.

#162 chore: rename git_push_stack to mergify_cli
  mergify_cli/__init__.py
  mergify_cli/commit_msg_hook.py
  mergify_cli/tests/test_mergify_cli.py
  poe.toml
  pyproject.toml
Labels: queued

#173 ci: disable semantic PR check on MQ PRs
  .github/workflows/semantic-pull-request.yaml
Labels: queued

#164 feat: get token through `gh auth token` if not provided by --token or GITHUB_TOKEN env var
  mergify_cli/__init__.py
Labels: skip changelog

#166 feat: Add control on draft or open status through a param
  mergify_cli/__init__.py
Labels: skip changelog, review threads unresolved

#167 feat: Define trunk through param --trunk/-t or git config mergify-cli.stack-trunk
  mergify_cli/__init__.py
Labels: skip changelog

#168 fix: Improve hook
  hooks/commit-msg
  mergify_cli/__init__.py
  mergify_cli/hooks/commit-msg
Labels: queued

#182 docs: Fix the config command and a link
  README.md
Labels: queued
