Repository Mergifyio/mergify-cli, pull requests merged in 2025-08, with the labels that each got.

#725 feat: add jenkins support
  mergify_cli/ci/detector.py
Labels: skip changelog

#736 fix(jenkins): get git branch correctly
  mergify_cli/ci/detector.py
  mergify_cli/tests/ci/test_detector.py
Labels: queued

#755 feat(mergify): deployments reporting method
  .mergify.yml
Labels: queued, skip changelog

#759 ci: ignore dependabot/mergify PR from release note
  .github/release.yml
Labels: queued
